export enum ActionType {
    CREATE_CARD = "createCard",
    DELETE_CARD = "delete",
    CREATE_TRACK = "createTrack",
    DELETE_TRACK = "deleteTrack",
    CREATE_USER = "createUser",
    LOGIN_USER = "loginUser",
    SORT_ATTRIBUTE = "sortAttribute",
    CREATE_STEP = "createStep",
    ADD_CV = "addCV",
    DELETE_CV = "deleteCv",
    CREATE_COMPANY = "createCompany",
    CREATE_POSITION = "createPosition",
    ADD_STEP_TO_TEMPLATE = "ADD_STEP_TO_TEMPLATE",
    DELETE_POSITION = "delete_position",
    CLEAR_TRACKS = "clear_tracks",
    CLEAR_COMPANYS = "clear_companys",
    CLEAR_CVS = "clear_cvs",
    CLEAR_USERS = "clear_users",
    CLEAR_CURR_USER = "clear_curr_user",
}
